
import java.applet.AudioClip;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Calderon
 */
public class Sinfonia extends javax.swing.JFrame {

    private Musicos guitarra;
    private Musicos violin;
    private Musicos flauta;
    private Musicos piano;
    private Musicos contrabajo;
    private Musicos arpa;
    private Musicos bateria;
    private Musicos cello;
    private Musicos congas;
    private Musicos trompeta;

    public Sinfonia() {
        initComponents();

        guitarra = new Musicos("Guitarrista", "sonidos/guitarra.wav");
        violin = new Musicos("Violinista", "sonidos/violin.wav");
        flauta = new Musicos("Flautista", "sonidos/flauta.wav");
        piano = new Musicos("Pianista", "sonidos/piano.wav");
        contrabajo = new Musicos("Contabajista", "sonidos/contrabajo.wav");
        arpa = new Musicos("Arpista", "sonidos/arpa.wav");
        bateria = new Musicos("Baterista", "sonidos/bateria.wav");
        cello = new Musicos("Cellista", "sonidos/cello.wav");
        congas = new Musicos("Conguero", "sonidos/conga.wav");
        trompeta = new Musicos("Trompetista", "sonidos/trompeta.wav");
        setLocationRelativeTo(this);
        ocultarNotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDirector = new javax.swing.JLabel();
        btnArpa = new javax.swing.JLabel();
        btnPiano = new javax.swing.JLabel();
        btnFlauta = new javax.swing.JLabel();
        btnFContrabajo = new javax.swing.JLabel();
        btnViolin = new javax.swing.JLabel();
        btnGuitarra = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        btnCello = new javax.swing.JLabel();
        btnCongas = new javax.swing.JLabel();
        btnBateria = new javax.swing.JLabel();
        btnTrompeta = new javax.swing.JLabel();
        notasPiano = new javax.swing.JLabel();
        notasCongas = new javax.swing.JLabel();
        notasGuitarra = new javax.swing.JLabel();
        notasArpa = new javax.swing.JLabel();
        notasTrompeta = new javax.swing.JLabel();
        notasFlauta = new javax.swing.JLabel();
        notasCello = new javax.swing.JLabel();
        notasContabajo = new javax.swing.JLabel();
        notasBateria = new javax.swing.JLabel();
        notasViolin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orquesta Sinfónica de Daniel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        btnDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/directorO.gif"))); // NOI18N
        btnDirector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDirectorMouseClicked(evt);
            }
        });
        jPanel1.add(btnDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 140, 180));

        btnArpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arpa.png"))); // NOI18N
        btnArpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArpaMouseClicked(evt);
            }
        });
        jPanel1.add(btnArpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 90, 110));

        btnPiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piano.png"))); // NOI18N
        btnPiano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPiano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPianoMouseClicked(evt);
            }
        });
        jPanel1.add(btnPiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 110));

        btnFlauta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flauta.png"))); // NOI18N
        btnFlauta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFlauta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFlautaMouseClicked(evt);
            }
        });
        jPanel1.add(btnFlauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 100, 130));

        btnFContrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrabajo.png"))); // NOI18N
        btnFContrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFContrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFContrabajoMouseClicked(evt);
            }
        });
        jPanel1.add(btnFContrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 90, 130));

        btnViolin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/violin.png"))); // NOI18N
        btnViolin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViolin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViolinMouseClicked(evt);
            }
        });
        jPanel1.add(btnViolin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 70, 110));

        btnGuitarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guitarra.png"))); // NOI18N
        btnGuitarra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuitarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuitarraMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuitarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 60, 110));

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLog);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 240, 420));

        btnCello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cello.png"))); // NOI18N
        btnCello.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCello.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCelloMouseClicked(evt);
            }
        });
        jPanel1.add(btnCello, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 70, 110));

        btnCongas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/congas.png"))); // NOI18N
        btnCongas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCongas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongasMouseClicked(evt);
            }
        });
        jPanel1.add(btnCongas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, 130));

        btnBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bateria.png"))); // NOI18N
        btnBateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBateriaMouseClicked(evt);
            }
        });
        jPanel1.add(btnBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 180, 150));

        btnTrompeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trompeta.png"))); // NOI18N
        btnTrompeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrompeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrompetaMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrompeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 220));

        notasPiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasPiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 60, 60));

        notasCongas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasCongas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 50));

        notasGuitarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasGuitarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 50, 50));

        notasArpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasArpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 50, 50));

        notasTrompeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasTrompeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, 50));

        notasFlauta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasFlauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 50, 50));

        notasCello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasCello, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 50, 50));

        notasContabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasContabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 50, 50));

        notasBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 50, 50));

        notasViolin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes.gif"))); // NOI18N
        jPanel1.add(notasViolin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escenario.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArpaMouseClicked
        if (arpa.isEstado()) {
            if (dormir) {
                arpa.dormir();
            } else {
                arpa.detener();
            }
        } else {
            arpa.start();
        }
        mostrarIcono(arpa, notasArpa);
        jTextAreaLog.append(arpa.getEstato() + "\n");

    }//GEN-LAST:event_btnArpaMouseClicked

    private void btnPianoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPianoMouseClicked
        if (piano.isEstado()) {
            if (dormir) {
                piano.dormir();
            } else {
                piano.detener();
            }
        } else {
            piano.start();
        }
        mostrarIcono(piano, notasPiano);
        jTextAreaLog.append(piano.getEstato() + "\n");
    }//GEN-LAST:event_btnPianoMouseClicked

    private void btnFlautaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlautaMouseClicked
        if (flauta.isEstado()) {
            if (dormir) {
                 mostrarIcono(flauta, notasFlauta);
                flauta.dormir();
            } else {
                flauta.detener();
            }
        } else {
            flauta.start();
        }
        mostrarIcono(flauta, notasFlauta);
        jTextAreaLog.append(flauta.getEstato() + "\n");
    }//GEN-LAST:event_btnFlautaMouseClicked

    private void btnFContrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFContrabajoMouseClicked
        if (contrabajo.isEstado()) {
            if (dormir) {
                contrabajo.dormir();
            } else {
                contrabajo.detener();
            }
        } else {
            contrabajo.start();
        }
        mostrarIcono(contrabajo, notasContabajo);
        jTextAreaLog.append(contrabajo.getEstato() + "\n");
    }//GEN-LAST:event_btnFContrabajoMouseClicked

    private void btnViolinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViolinMouseClicked
        if (violin.isEstado()) {
            if (dormir) {
                violin.dormir();
            } else {
                violin.detener();
            }
        } else {
            violin.start();
        }
        mostrarIcono(violin, notasViolin);
        jTextAreaLog.append(violin.getEstato() + "\n");
    }//GEN-LAST:event_btnViolinMouseClicked

    private void btnGuitarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuitarraMouseClicked
        if (guitarra.isEstado()) {
            if (dormir) {
                guitarra.dormir();
            } else {
                guitarra.detener();
            }
        } else {
            guitarra.start();
        }

        mostrarIcono(guitarra, notasGuitarra);
        jTextAreaLog.append(guitarra.getEstato() + "\n");
    }//GEN-LAST:event_btnGuitarraMouseClicked

    private void btnCelloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCelloMouseClicked
        // TODO add your handling code here:

        if (cello.isEstado()) {
            if (dormir) {
                cello.dormir();
            } else {
                cello.detener();
            }
        } else {
            cello.start();
        }

        mostrarIcono(cello, notasCello);
        jTextAreaLog.append(cello.getEstato() + "\n");
    }//GEN-LAST:event_btnCelloMouseClicked

    private void btnCongasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongasMouseClicked

        if (congas.isEstado()) {
            if (dormir) {
                congas.dormir();
            } else {
                congas.detener();
            }
        } else {
            congas.start();
        }

        mostrarIcono(congas, notasCongas);
        jTextAreaLog.append(congas.getEstato() + "\n");
    }//GEN-LAST:event_btnCongasMouseClicked

    private void btnBateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBateriaMouseClicked
        if (bateria.isEstado()) {
            if (dormir) {
                bateria.dormir();
            } else {
                bateria.detener();
            }
        } else {
            bateria.start();
        }
        mostrarIcono(bateria, notasBateria);
        jTextAreaLog.append(bateria.getEstato() + "\n");
    }//GEN-LAST:event_btnBateriaMouseClicked

    private void btnTrompetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrompetaMouseClicked

        if (trompeta.isEstado()) {
            if (dormir) {
                trompeta.dormir();
            } else {
                trompeta.detener();
            }
        } else {
            trompeta.start();
        }

        mostrarIcono(trompeta, notasTrompeta);
        jTextAreaLog.append(trompeta.getEstato() + "\n");
    }//GEN-LAST:event_btnTrompetaMouseClicked

    private void btnDirectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDirectorMouseClicked
        dormir = !dormir;
        if (dormir) {
            jTextAreaLog.append("\nAl presionar, los músicos \ndescansaran 3 segundos\n");
        } else {
            jTextAreaLog.append("\nAl presionar, los músicos \ndejaran de tocar.\n");
        }
    }//GEN-LAST:event_btnDirectorMouseClicked

    private void mostrarIcono(Musicos hilo, JLabel label) {
        if (hilo.isEstado()) {
            label.setVisible(true);
        } else {
            label.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sinfonia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sinfonia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sinfonia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sinfonia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sinfonia().setVisible(true);
            }
        });
    }

    private boolean dormir;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnArpa;
    private javax.swing.JLabel btnBateria;
    private javax.swing.JLabel btnCello;
    private javax.swing.JLabel btnCongas;
    private javax.swing.JLabel btnDirector;
    private javax.swing.JLabel btnFContrabajo;
    private javax.swing.JLabel btnFlauta;
    private javax.swing.JLabel btnGuitarra;
    private javax.swing.JLabel btnPiano;
    private javax.swing.JLabel btnTrompeta;
    private javax.swing.JLabel btnViolin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JLabel notasArpa;
    private javax.swing.JLabel notasBateria;
    private javax.swing.JLabel notasCello;
    private javax.swing.JLabel notasCongas;
    private javax.swing.JLabel notasContabajo;
    private javax.swing.JLabel notasFlauta;
    private javax.swing.JLabel notasGuitarra;
    private javax.swing.JLabel notasPiano;
    private javax.swing.JLabel notasTrompeta;
    private javax.swing.JLabel notasViolin;
    // End of variables declaration//GEN-END:variables

    private void ocultarNotas() {
        notasArpa.setVisible(false);
        notasBateria.setVisible(false);
        notasCello.setVisible(false);
        notasCongas.setVisible(false);
        notasContabajo.setVisible(false);
        notasFlauta.setVisible(false);
        notasGuitarra.setVisible(false);
        notasPiano.setVisible(false);
        notasTrompeta.setVisible(false);
        notasViolin.setVisible(false);
    }

}
